### ISSUE TITLE
missing github repo link in the docs 

### ISSUE THREAD

**Issue by EvolOfThings** [jarrodwatts/evmkit#2]
I noticed that there's no GitHub link on the docs site. 
It would be better if we can include GitHub link on the side nav tabs under Twitter and Discord links.

<img width="450" alt="Screenshot 2023-07-03 at 4 34 17 PM" src="https://github.com/jarrodwatts/evmkit/assets/12666706/afee23dd-3330-4c96-971b-02f1187da1b7">

**Comment by EvolOfThings** [comment]
@jarrodwatts if you think it's necessary, I'll work on it.

**Comment by jarrodwatts** [comment]
Would be great if you could do that! @EvolOfThings

**Comment by jarrodwatts** [comment]
btw, the docs repo is separate to get it to cooperate with Mintlify atm - https://github.com/jarrodwatts/evmkit-docs

**Comment by EvolOfThings** [comment]
got it! thank you @jarrodwatts

**Comment by EvolOfThings** [comment]
this was fixed on a different repo [here](https://github.com/jarrodwatts/evmkit-docs/pull/1#event-9708689891)

I shall close this issue here @jarrodwatts
