### ISSUE TITLE
Error when trying to setup project using the CLI

### ISSUE THREAD

**Issue by jimzord12** [jarrodwatts/evmkit#3]
Greetings,

I am new web3 dev (this is the issue I have ever commited xD) and as I am following you through your yt videos. I wanted to check out this new evm-kit framework.

Sadly, whenever I try to run the (even with admin privileges): npx evmkit create my-evmkit-app
I get the following:

## ⛔ The Error
PS C:\Users\BlockHead\Desktop\New-folder> npx evmkit create my-evmkit-app

███████╗██╗░░░██╗███╗░░░███╗ ██╗░░██╗██╗████████╗
██╔════╝██║░░░██║████╗░████║ ██║░██╔╝██║╚══██╔══╝
█████╗░░╚██╗░██╔╝██╔████╔██║ █████═╝░██║░░░██║░░░
██╔══╝░░░╚████╔╝░██║╚██╔╝██║ ██╔═██╗░██║░░░██║░░░
███████╗░░╚██╔╝░░██║░╚═╝░██║ ██║░╚██╗██║░░░██║░░░
╚══════╝░░░╚═╝░░░╚═╝░░░░░╚═╝ ╚═╝░░╚═╝╚═╝░░░╚═╝░░░

 💎 evmkit v0.0.3 💎

Creating a new EVM Kit project in C:\Users\BlockHead\Desktop\New-folder\my-evmkit-app.

Downloading files from repo. This might take a moment.
Installing packages. This might take a couple of minutes.

Usage Error: No project found in /C:/Users/BlockHead/Desktop/New-folder/my-evmkit-app

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]

{
  command: 'yarn install'
}

- I have installed yarn (v3.3.0)
- I have also used the 'npm' flag to make run with npm but it produced a similar error

## Notes
Although I am quite new (1.5 years of exp) in the web2-3 dev, I think this error indicates that the CLI can not find the sub-directories and automatically install their deps. Maybe, the tool needs to wait until the subfolders are created before trying to install the deps. I played around with GPT-4 and it suggests the following:

_Working Directory: The tool might not be correctly setting or navigating to the project directory before trying to install the dependencies._

Finally, I do understand that this not a serious issue as it is just meant to automate the cloning and deps, extnetions installment procedures. Thanks a lot for the awesome content you provide to this community, its trully increadible!

**Comment by jarrodwatts** [comment]
Hey, thanks for the detailed issue report!

I'm getting the same issue as well. I think this is a bug in the CLI. Let me try fix this now

**Comment by jarrodwatts** [comment]
Hey, @jimzord12 could you try the latest version?

`npx evmkit@latest create my-evmkit-app`

**Comment by jimzord12** [comment]
No error is thrown now, however the deps are not automatically downloaded. My terminal output:
```
PS C:\Users\BlockHead\Desktop\New-folder> npx evmkit@latest create my-evmkit-app

███████╗██╗░░░██╗███╗░░░███╗ ██╗░░██╗██╗████████╗
██╔════╝██║░░░██║████╗░████║ ██║░██╔╝██║╚══██╔══╝
█████╗░░╚██╗░██╔╝██╔████╔██║ █████═╝░██║░░░██║░░░
██╔══╝░░░╚████╔╝░██║╚██╔╝██║ ██╔═██╗░██║░░░██║░░░
███████╗░░╚██╔╝░░██║░╚═╝░██║ ██║░╚██╗██║░░░██║░░░
╚══════╝░░░╚═╝░░░╚═╝░░░░░╚═╝ ╚═╝░░╚═╝╚═╝░░░╚═╝░░░


 💎 evmkit v0.0.3 💎

Creating a new EVM Kit project in C:\Users\BlockHead\Desktop\New-folder\my-evmkit-app.

Downloading files from repo. This might take a moment.
Initialized a git repository.

Success! Created my-evmkit-app at C:\Users\BlockHead\Desktop\New-folder\my-evmkit-app
We suggest that you begin by typing:

  cd my-evmkit-app

PS C:\Users\BlockHead\Desktop\New-folder> 
```
Unrelated question, why choose ethers version  "5.4.7" instead of "5.7.2" (we all know why not to use v6+ xD). In npm. 5.7.2 has by far the most weekly downloads.

**Comment by jarrodwatts** [comment]
Cool I'm happy with it not auto-installing as those instructions are in the getting started anyways.

Hmm, no specific reason, happy to update it to 5.7.2. I'll be doing a round of updates to use the latest shadcn/ui and thirdweb changes in the next few days as well, I'll include an upgrade to that Ethers version - thanks for pointing it out.

**Comment by jarrodwatts** [comment]
Btw here's most of those changes - https://github.com/jarrodwatts/evmkit/pull/4
